### PR TITLE
Remove extra group view/.js files

### PR DESCRIPTION
**Pull request by lvogt**
This removes the extraneous group_view.php and group_graph.js files and simply adds support directly in the usual view files if the variable group_support is set.

This hopefully simplifies keeping the interface uptodate and both "views" in sync.

Beware: This has been only moderately tested by me.

### CODE REVIEW

**Comment by glynhudson** [comment]
@emrysr any chance you could test this and feedback. Thanks

**Comment by lvogt** [comment]
Sorry about the forced push - I didn't expect github to pick it up, since I only corrected some author info...

The last commit switches the layout of the normal feed list to the "div-based" layout from the group view. I think having a mostly similar layout is a good idea and I like this variant better - if you disagree I can revert the commit (or you can just cherry-pick the first...)

**Comment by lvogt** [comment]
The last 6 commits are mainly some minor UI clean-ups - again feel free to omit them...

**Comment by TrystanLea** [comment]
Hello @lvogt it looks like we got mixed up as part of work on the sidebar. Would it be hard to rebase your changes based on the latest master?

**Comment by TrystanLea** [comment]
I will close the pull request for now and consider these changes when I next get a chance to revisit the group module.

**Pull request closed without merging**
