### PR TITLE
Date enhancements

### PR DESCRIPTION
**Pull request by CDuffers**
Changed the date time entry from second since epoch to human readable format

### CODE REVIEW

**Comment by CDuffers** [comment]
Sorry, forgot a couple of screenshots to show the differences.

Here's a view of how it looks within the graph visualisation page:
image

And then the base delivery when embedded within a dashboard (only the expand icon has changed):
image

And then with the date time picker visible:
image

**Comment by glynhudson** [comment]
Wow, nice work. This works really great, a *very* useful addition, Thanks a lot.

**Comment by alan-dodd** [comment]
Hello: if I strike the 'D' (day) button, on the bottom of the graph I can see only time of day, not month/date/time as per Week or Month visualization. Is there a way to change this setting? 
Because it becomes confusing if from that graph I start clicking '<' or '>' to browse data: after a while I don't know any more to which day data belongs.
Same thing happens looking at feeds: if I zoom in a day, I can't see date string any more. Thank you.
day
days

**Comment by CDuffers** [comment]
Hi @alan-dodd ,

Flot is used for the graphs and we rely upon its logic to determine the level of info placed along the x-axis. If we attempt to force it to use full date and time for all graphs, then this is likely to get pretty crowded. or otherwise significantly reduce the number of tick marks and thereby markers being quite wide apart and thereby difficult to read.

Where are you using the graph? Within the "Setup -> Graph"? If so, then the start and end times and dates are shown beneath.

You can otherwise hover the mouse over a data point and the tooltip pop-up will show the date and time.

Please let me know if you have a suggestion of how to cover an approach which cover graphs showing a total of a few minutes to graphs showing an year or more.

**Pull request merged**
